//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bookingsByBita1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int AptID { get; set; }
        public string EmpID { get; set; }
        public int CustID { get; set; }
        public System.DateTime AptDate { get; set; }
        public System.TimeSpan AptTime { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
