//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bookingsByBita1._0
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HairSalonDBContext : DbContext
    {
        public HairSalonDBContext()
            : base("name=HairSalonDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Appointment> Appointments { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
    
        public virtual ObjectResult<Nullable<int>> spGetCustID(string email, string phone)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("spGetCustID", emailParameter, phoneParameter);
        }
    
        public virtual ObjectResult<spShowAllHairStylist_Result> spShowAllHairStylist()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spShowAllHairStylist_Result>("spShowAllHairStylist");
        }
    
        public virtual ObjectResult<spShowAllSchedule_Result> spShowAllSchedule()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spShowAllSchedule_Result>("spShowAllSchedule");
        }
    
        public virtual ObjectResult<spShowTodaySchedule_Result> spShowTodaySchedule()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spShowTodaySchedule_Result>("spShowTodaySchedule");
        }
    }
}
